---
- name: Include vars
  include_vars:
    #dir: '{{playbook_dir}}/roles/group_vars'
    dir: '/home/den/repos/ipr/devops_school_ansible/roles/group_vars'

- name: nginx user creation
  user:
    name: '{{ nginx_user }}'
    state: present

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Generate Nginx config
  template:
    src: nginx.conf.j2
    dest: '/etc/nginx/nginx.conf'
    mode: 444
  notify: Restart Nginx

- name: Start and enable Nginx on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: create static folder
  file:
    path: '{{ static_files_location }}'
    state: directory
    mode: 755

- name: Copy index.php
  copy:
    src: ./linfo-4.0.6/index.php
    dest: '{{ static_files_location }}/index.php'
    mode: 444
  notify: Restart Nginx

- name: Copy static
  copy:
    src: ./linfo-4.0.6/layout
    dest: '{{ static_files_location }}'
    mode: 444
  notify: Restart Nginx
