---
- name: converge
  hosts: balancer-1
  vars:
    version: "4.0.6"
    remote_tmp: "/tmp/.ansible-${USER}/tmp"
  pre_tasks:
    - name: testinfra dependencies
      apt:
        name: iproute2
        state: present
  roles:
    - nginx
